version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: /bin/bash
    tty: true
    volumes:
      - .:/websocket-demo
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/backend/pg/data:/var/lib/postgresql/data
